name: flat_icons_flutter
description: A new Flutter package.
version: 1.0.1
author: Duncan Adjei <duncanadjei@gmail.com>
homepage: https://github.com/duncanadjei/flat_icons_flutter

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
   fonts:
     - family: FlatIcons
       fonts:
         - asset: lib/fonts/FlatIcon.ttf
           weight: 400
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.io/custom-fonts/#from-packages
